[package]
name = "actix-react-clerk"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
actix-files = "0.6.5"
openssl-sys = { version = "0.9.9", features = ["vendored"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shuttle-actix-web = "0.53.0"
shuttle-runtime = "0.53.0"
chrono = "0.4.40"
futures = "0.3.31"
tokio = "1.44.1"
unicode-segmentation = "1.12.0"
reqwest = "0.12.15"
tracing = "0.1.41"
